[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'github/copilot.vim'
#depend node.js v14+ refs:https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04-ja

[[plugins]]
repo = 'koron/nyancat-vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
on_fit = ['python']
merged=0
rev="release"

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'


# [[plugins]]
# repo = 'vim-denops/denops.vim'
#
# [[plugins]]
# repo = 'Shougo/ddu-ui-ff'
#
# [[plugins]]
# repo = 'Shougo/ddu-source-file_rec'
#
# [[plugins]]
# repo = 'Shougo/ddu-filter-matcher_substring'
#
# [[plugins]]
# repo = 'Shougo/ddu-kind-file'
#
# [[plugins]]
# repo = 'Shougo/ddu.vim'
